services:
  app:
    image: ${DOCKERHUB_USERNAME}/cloud-app:${IMAGE_TAG}
    container_name: cloud-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SERVER_PORT: 8080
      TZ: Asia/Seoul
    ports:
      - "8080:8080"

    restart: always

